### ISSUE TITLE
Enhancement: Ability to have CRON jobs inside of container

### ISSUE THREAD

**Issue by shotah** [mide/minecraft-overviewer#109]
Feature: Ability to have a container that periodically runs and updates the map. Currently I set this up externally but would be nice to have inside the container and keep it long lived. 

[Examples](https://www.cloudsavvyit.com/9033/how-to-use-cron-with-your-docker-containers/)

**Comment by mide** [comment]
Closing in favor of https://github.com/mide/minecraft-overviewer/pull/105, please see conversations there.
