### ISSUE TITLE
Update Overviewer for Leaflet

### ISSUE THREAD

**Issue by magneticflux-** [mide/minecraft-overviewer#11]
Using the Google Maps API key is outdated now that they have [switched to Leaflet](https://overviewer.org/blog/2018/5/6/overviewer-switches-to-leaflet/). I'm not sure what else needs to be done; it looks like you already always pull the most up-to-date version of Overviewer.

**Comment by magneticflux-** [comment]
It seems that pulling the latest docker image doesn't actually update to the latest Overviewer. This is the generated file that I get:
```
<!DOCTYPE html>
<html>
<head>

<title>Minecraft Overviewer</title>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Minecraft-Overviewer 0.12.204 (22b9ab3)" />
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

<link rel="stylesheet" href="overviewer.css" type="text/css" />

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=********"></script>

<script type="text/javascript" src="underscore.js"></script>
<script type="text/javascript" src="backbone.js"></script>
<script type="text/javascript" src="overviewerConfig.js"></script>
<script type="text/javascript" src="overviewer.js"></script>
<script type="text/javascript" src="baseMarkers.js"></script>

</head>

<!-- Generated at: Wed, 09 May 2018 19:36:31 UTC -->
<body onload="overviewer.util.initialize()">
 <div id="mcmap">
     <div id="NoJSWarning" style="color:white; background-color:black">
         If you can see this message, there is likely a problem loading the Overviewer javascript components.
         Check the javascript console for error messages.
     </div>
 </div>
</body>
</html>
```
Note the Overviewer version is `0.12.204`, not `0.12.259`. Is there some cache I could clear to force the updated version to be downloaded?

**Comment by magneticflux-** [comment]
Results of more investigation:
I can start a shell using `docker run -it -u root sh mide/minecraft-overviewer:latest` and then run `apt-get update` and `apt-get upgrade`, which installs the newest version of Overviewer. I'm still not sure why the `apt-get install` doesn't grab the latest version even though there is an `apt-get update` right before it.

**Comment by magneticflux-** [comment]
The solution (or workaround?) that finally worked:
```
git clone https://github.com/mide/minecraft-overviewer.git
```
```
cd minecraft-overviewer
```
```
docker build . -t mide/minecraft-overviewer
```
Now, running `docker run mide/minecraft-overviewer overviewer.py --version` displays `0.12.260`.

**Comment by mide** [comment]
Thanks for bringing this to my attention. The problem is the Docker build doesn't rebuild on their git pushes, so it gets stale. I'll look into that.

I will also look at removing Google tokens from the code.

**Comment by mide** [comment]
The latest build fixes this, thanks for the help.

I am working on some better automation around regular builds.

**Comment by mide** [comment]
I have deployed a new version of the builds via 9929369ea07ba0413ecf555bfe2f1a6713eba0f5, that will ensure it gets updated on a regular basis.
