### ISSUE TITLE
Modify github actions workflow to build arm64 container

### ISSUE THREAD

**Issue by jguizarj** [mide/minecraft-overviewer#111]
Hi, @mide! first of all, thank you for your amazing job with this repo!

I'm currently running a Minecraft server on arm64. To run the overviewer container I had to clone your repo and re-build the container directly in arm64 (RHEL8).

It worked flawlessly without any modification to the Dockerfile (the ~~ubuntu~~ debian base image is available in arm64) and I was able to schedule a systemd timer to run overviewer every 12 hours. The only problem is that I have to pull the changes and build the container manually every time an update is needed.

**Design proposal:**

1. Add an action in the .yaml workflow to use `docker/setup-qemu-action@v1`
2. Add An action in the .yaml workflow to use `docker/setup-buildx-action@v1` for multi arch container build
3. Add the `platforms` input to the `docker/build-push-action@v2` action to target `linux/amd64` and `linux/arm64`

**Comment by mide** [comment]
Closed with #112, thanks for the contribution!
