### ISSUE TITLE
[FEATURE REQUEST] Support Bedrock Servers

### ISSUE THREAD

**Issue by IzaacJ** [mide/minecraft-overviewer#120]
Hello.
It seems that it's not possible to set this up for Bedrock Servers, even though Overviewer works with Bedrock maps.

The big issue is the path it is looking at, assuming that the level data is directly in `home/minecraft/server/worlds`.
When bind-mounting a Bedrock Server to the server directory, the actual level data is located in `/home/minecraft/server/worlds/[LevelName]`.

**Comment by mide** [comment]
Sorry for the long delay in response, is this something you could just use different mountpoints to address? So you could run with this change: 
```diff
 docker pull mide/minecraft-overviewer:latest
 docker run \
   --rm \
   -e MINECRAFT_VERSION="1.17" \
-  -v /home/user/minecraft/:/home/minecraft/server/:ro \
+  -v /home/user/minecraft/[Level Name]:/home/minecraft/server/:ro \
   -v /srv/http/minecraft/:/home/minecraft/render/:rw \
   mide/minecraft-overviewer:latest
```
Or is there more to it than that? I'm not familiar with Bedrock hosting.

**Comment by mide** [comment]
Given the lack of response (sorry for my contribution to the slowness on this issue), I am going to close this with the suggestion of using different mountpoints to better suit your needs. You can also load in a custom `config.py` if needed.
