### ISSUE TITLE
Minecraft-Overviewer Doesn't Support 1.13 Map Format

### ISSUE THREAD

**Issue by mide** [mide/minecraft-overviewer#27]
The rendering software that this docker image makes use of (Minecraft Overviewer) doesn't yet support the map format released during `1.13`. See https://github.com/overviewer/Minecraft-Overviewer/issues/1454 for information on their progress. 

This container should update within a day due to the automated build, but I'll keep tabs on it, too.

**Comment by mide** [comment]
According to https://github.com/overviewer/Minecraft-Overviewer/issues/1454#issuecomment-408907203, we may not see support for the `1.13` map format for some time.

**Comment by shotah** [comment]
Looks like they have added a branch just for 1.13. It's all happening pretty quick though. https://github.com/gmcnew/Minecraft-Overviewer/tree/minecraft113

**Comment by mide** [comment]
Correct, thanks for updating this @shotah. I will wait for it to hit the `master` branch for reliability reasons.

**Comment by mixxit** [comment]
any news?

**Comment by mide** [comment]
Hi @mixxit! I would suggest taking a look at https://github.com/overviewer/Minecraft-Overviewer/issues/1454, as the problem with this lies with the upstream project `Minecraft-Overviewer`. This repository simply includes it and wraps it into a little Docker container. 

It does seem the team is actively working on it since there is now a [Minecraft 1.13 GitHub tag](https://github.com/overviewer/Minecraft-Overviewer/labels/Minecraft%201.13) on their project.

**Comment by Slashbunny** [comment]
The upstream merge request has been merged with 1.13 support 🎉

**Comment by mide** [comment]
Thanks for the updates everyone! I haven't validated it, but I think the automation in the container should just work. For those wanting to force the old version, you should be able to use `mide/minecraft-overviewer:2019-01` instead of `:latest`.
