### ISSUE TITLE
Adding environment variable to run the POI

### ISSUE THREAD

**Issue by snppla** [mide/minecraft-overviewer#3]
This is a feature request to add an environment variable to only run genpoi. It should be pretty straightforward to add that this feature. I like to run gen poi more often since it's fast so I can update player locations faster. I could add this feature

**Comment by mide** [comment]
Yep, I'm completely in favor of adding this.

**Comment by snppla** [comment]
Great, I can make the change if you want.

**Comment by mide** [comment]
Thanks! If you have the cycles, that'd help me. We'll want to make sure it's backwards compatible and that the option is optional (if it's not set, the logic doesn't break).

**Comment by mide** [comment]
Added in https://github.com/mide/minecraft-overviewer/pull/13.
