### ISSUE TITLE
Container fails to launch

### ISSUE THREAD

**Issue by gutyex** [mide/minecraft-overviewer#36]
When started, the container exits with error:
/home/minecraft/entrypoint.sh: line 11: python: command not found,

Image: mide/minecraft-overviewer:latest

**Comment by mide** [comment]
Interesting; I just saw someone update to Python3 - I wonder if it's related. I filed https://github.com/mide/minecraft-overviewer/issues/35 the other day to investigate.

**Comment by mide** [comment]
Should be solved by #37 and/or #38.
