### ISSUE TITLE
Adding google maps api key environmental variable.

### ISSUE THREAD

**Issue by snppla** [mide/minecraft-overviewer#4]
If the map is accessed publicly, it needs a google maps api key. Overviewer doesn't directly have this feature, but using sed you can add the key to the generated index.html.

**Comment by mide** [comment]
Sounds good to me. I'm in favor of this addition.

**Comment by snppla** [comment]
I can make the change if you want.

**Comment by mide** [comment]
Sure, if you've got the time, that's be a huge help. Should we consider the environment variable a "required" one? (should the container error if it's not set or just continue with defaults)

**Comment by snppla** [comment]
I don't think it should be required, especially since overviewer doesn't
provide an option to include it and runs without it.

**Comment by mide** [comment]
👍 Sounds good to me. Thanks!

**Comment by mide** [comment]
Closed by #6 and db29b3057c5ab0656771da4afdd58e8a86573346.
