### ISSUE TITLE
ADDITIONAL_ARGS incorrectly passes arguments to genpoi

### ISSUE THREAD

**Issue by bagobones** [mide/minecraft-overviewer#45]
`/usr/bin/overviewer.py --genpoi: error: unrecognized arguments: --no-tile-checks`

Looks like the first phase of scanning works correctly but the extra arguments stop POI generation from working.

**Comment by mide** [comment]
Interesting - I'll take a look this week, thanks for the report.

**Comment by bagobones** [comment]
As a side note if anyone stumbles on this issue basically all of the additional args can be controlled in the config file http://docs.overviewer.org/en/latest/config/

**Comment by mide** [comment]
I've been thinking about this issue a fair amount. @bagobones What do you think about the idea that this actually a bug with the upstream [Minecraft Overviewer](https://github.com/overviewer/Minecraft-Overviewer/issues)? Their [documentation on running the tool](http://docs.overviewer.org/en/latest/running/) does not mention that some sets of arguments are mutually exclusive? 

In other words, after reading their documentation, both command line calls should be able to handle the same arguments.

**Comment by bagobones** [comment]
@mide technically the CLI fails gracefully and tells you what is not compatible, it is just because this docker is forcing a POI only generation and passing all the args that this fails.

I am actually not sure if ANY of the CLI args are compatible with --genpoi , maybe -p <procs>, --processes <procs> are but I haven't tested. If none of them are another solution would be just not to pass any of the additional args to --genpoi

I have worked around this issue by putting everything in the config file. Having them split out however will likely be the simplest option with the most potential future compatibility allowing the user to chose what to pass.

**Comment by mide** [comment]
Thoughts:
1. > technically the CLI fails gracefully and tells you what is not compatible

     The behavior that the CLI has should continue into this Docker image. When it is "failing gracefully", does it still render POI? Or are you just saying the error message is helpful? If it doesn't render, I wouldn't say it's a graceful failure. I expect the Docker image and the CLI directly to share the same root behavior.
1. When you say   
    > it is just because this docker is forcing a POI only generation and passing all the args that this fails.

    There is the `RENDER_POI` environment variable that controls if POI is rendered, so I wouldn't say it's forced. 

1. I have concerns about splitting apart these environment variables, because if there was an option that's being used and people were unaware of the change, their parameter would stop being passed into the POI render process.

**Comment by bagobones** [comment]
1. When using it via CLI you would call them separately and have the opportunity to pass different parameters. So no they don't behave the same the docker does both every time.

2. I really haven't looked that close at how it works, I wanted POIs, the docker appears to call over viewer for a render then call it again to generate POI when that flag is set. 

3. I worked around it with the config file after trying to do with passing ARGs to the docker.. If I was using normal CLI I could call over viewer twice with the correct ARGs, in the docker and having the RENDER_POI environment variable set it doesn't work.

At this point it now works for me by using the config file, it is your docker just found a case that didn't work.. Report it upstream or fix it upstream if you feel it should just ignore the arguments.

**Comment by mide** [comment]
Okay. Thanks for the report. I will investigate further and likely file something upstream. I don’t want to break anyone’s existing tooling and I want to make sure I understand the problem before merging changes. 

Thanks again.

**Comment by mide** [comment]
Fixed in https://github.com/mide/minecraft-overviewer/pull/46, closing.
