### ISSUE TITLE
merge 1.15 overviewer updates

### ISSUE THREAD

**Issue by bagobones** [mide/minecraft-overviewer#47]
According to discord I believe the main overviewer code has been update so overviewer doesn't error out on 1.15 worlds. It doesn't contain the new blocks but it will at least run and not crash I believe.

**Comment by mide** [comment]
Taking a look; I've got an automatic build but perhaps it hasn't picked up these changes yet.

**Comment by mide** [comment]
Can you point to where Minecraft Overviewer doesn't error on 1.15 worlds? I just tried and I'm hitting https://github.com/overviewer/Minecraft-Overviewer/issues/1687 (currently open).

**Comment by bagobones** [comment]
CounterPillow mentioned it over in discord.

https://discordapp.com/channels/323571122543132672/323571122543132672

"CounterPillowLast Tuesday at 2:16 PM
1.15 worlds should work now
needed some adjustments in the biome handling code"

Maybe it hasn't been merged yet.

**Comment by CounterPillow** [comment]
It has been merged, you just need 1.14 textures. We don't use 1.15 textures yet.

**Comment by bagobones** [comment]
Guess I better pull the latest image and give it a go then.

**Comment by mide** [comment]
So it sounds like we can try running with `MINECRAFT_VERSION=1.14`, but I haven't tested that and won't have a chance until later.

**Comment by bagobones** [comment]
I can see the build has updated in the logs so I plan on giving it a go in the next few days. My users really want 1.15 but are not willing to give up overviewer.

**Comment by mide** [comment]
Yeah, I’m not proposing limiting your users. I’m suggesting running overviewer with 1.14, on a 1.15 map. My understanding leads me to believe that would work.

**Comment by bagobones** [comment]
I understood that...

I have re-pulled my image, checked that the version is higher in the logs
I will set the environment variable for 1.14 for compatible textures..

Should be all good.
