### ISSUE TITLE
End & Nether

### ISSUE THREAD

**Issue by anthr76** [mide/minecraft-overviewer#52]
I notice that in the logs the container is looking for the end and nether world. Though my world name is survival. So I had my bind mount as `${HOME}/Docker/mcnew/mc-server-1/survival:/home/minecraft/server/world`

Is there an elegant way to get my nether and end on the over-viewer as well?

**Comment by mide** [comment]
I haven't had a chance to look, but hope to soon.

**Comment by mide** [comment]
Hey @anthr76 - This definitely seems like something the image should support. I would expect the mounting to work the way you have it. I'll have to see if I can make a test case and see I can reproduce.

_PS - I see you're in NY. Hope you're doing okay._

**Comment by mide** [comment]
Are you passing any specific configuration? Can you share how you're launching the render?

**Comment by anthr76** [comment]
Sure, I have since shut the server at the very moment but can develop a test environment tonight.

**Comment by mide** [comment]
Closing as stale. Feel free to re-open if this is still an issue.
