### ISSUE TITLE
Running on a live world causes tile corruption

### ISSUE THREAD

**Issue by magneticflux-** [mide/minecraft-overviewer#53]
It appears that chunks touched by the server during a render may be swapped or otherwise corrupted: https://github.com/overviewer/Minecraft-Overviewer/issues/1178.

A workaround is to RCON into the server and run `/save-off` and `/save-all` before the render and run `/save-on` after the render.

**Comment by mide** [comment]
I haven't had a chance to look, but hope to soon.

**Comment by mide** [comment]
This will be solved by #54. It's an upstream issue, but we're working on adding the workaround.
