### ISSUE TITLE
Exclude "-- RENDER --" from sign POIs on the map

### ISSUE THREAD

**Issue by magneticflux-** [mide/minecraft-overviewer#55]
It would be nice to render signs on the map without always having to see `-- RENDER --` at the end of them.

I'll work on a PR for this tomorrow probably.

**Comment by mide** [comment]
That's fine; I'd like to find a way to parameterize this, because this is a feature I like (allows for hidden bases, keeps the map from being cluttered).

**Comment by mide** [comment]
Closed by #56

**Comment by mide** [comment]
Actually, it just dawned on me this is slightly different than what I implemented. I will re-open and take a whack at it.

**Comment by magneticflux-** [comment]
I just read over it and it seems like it's parameterized fine, it's just that it doesn't strip the render phrase 😄. Maybe just call `str.replace(sign_filter_string, "")` on the returned string? That might strip more than necessary, but I can't imaging someone needing `-- RENDER --` multiple times in a sign.

Edit: The `<br/>` tags might also add extra space at the bottom of short signs; idk what empty sign lines return on `poi['TextN']` or how `join` affects them.

**Comment by mide** [comment]
#63 should do it for real. I have tracked the work to remove extra spaces in #61. There is now an option for users to specify how the lines are joined.

**Comment by mide** [comment]
Was actually solved in #63.
