### ISSUE TITLE
Ability to use custom Overviewer build

### ISSUE THREAD

**Issue by Smoria** [mide/minecraft-overviewer#80]
Could you please add ability to use custom Overviewer build, and not one fetched from repository. Since Overviewer devs are pushing fixes not so often, this will be very nice feature.

Something like using volume
`-v /custom-build:/home/overviewer:ro`
Where `/custom-build` contains overviewer files(overviewer.py etc.)

**Comment by mide** [comment]
@Smoria would #91 meet your needs? Or do you still want to be able to run a custom build?

**Comment by Smoria** [comment]
Seems like it! Thanks)
