### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [mide/minecraft-overviewer#96]
When running in a 1.17 env it returns
```
(Remember, this version of Overviewer requires a 1.16-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar
```

**Comment by bagobones** [comment]
Overviewer 0.17.0 version with 1.17 support has been released https://github.com/overviewer/Minecraft-Overviewer/releases/tag/v0.17.0

**Comment by F-Node-Karlsruhe** [comment]
Still getting:
` E Could not find the textures while searching for 'assets/minecraft/textures/block/grass_path_top.png'. Try specifying the 'texturepath' option in your config file.`

even though it is fixed in the repo already. But that run soon :)
