### ISSUE TITLE
Windows says it can't run Overviewer, then the command prompt says "Acess is denied"

### ISSUE THREAD

**Issue by locobeta55** [mide/minecraft-overviewer#99]
I recently made a couple maps with overviewer, but tried to make another and this happened. Just wanted to know if there is a fix or if I should re download overviewer.

**Comment by mide** [comment]
Hi there! I haven't tested this on Windows. Can you post the whole error? Is it still happening? 

It sounds like a file permission issue, which I need to properly document/enhance in #72.

**Comment by locobeta55** [comment]
Hi, it's been a while since I originally posted that error, and since then
I have gotten it to work with zero issues. Sadly I don't have the original
error anymore, but all it did say was just "Access is denied".

**Comment by mide** [comment]
Okay, thanks for following up. I'm going to close this out and track the permissions documentation in the mentioned ticket.
